### ISSUE TITLE
Nit: __init__ return value and docstring rtype in conflict

### ISSUE THREAD

**Issue by JnyJny** [BolieRide/colorpicker#1]
https://github.com/BolieRide/colorpicker/blob/082aadf922be950d3d87d09d1c7a8dd1bcfdd733/colorpicker/picker.py#L8

`__init__` methods are not expected to have a return value, and if it does return something it's ignored by the class instance creation machinery. Your docstring indicates that `__init__` has a return type of `object` while the type annotation of the return value `-> None:` indicates that nothing is returned. 

It's a nit but we strive to not confuse the reader and erode their confidence in our code.

**Comment by BolieRide** [comment]
Removed that from the file.  I believe it came in through PyCharm. I am looking into how that happened.
