### ISSUE TITLE
Add `setup.py` to project:

### ISSUE THREAD

**Issue by JnyJny** [BolieRide/colorpicker#2]
Add a `setup.py` file to the main directory of the project configured with information about the project.  Follow this [tutorial][1] to build your `setup.py` and of course ask questions when/if you get stuck.  The `setup.py` is packaging information that `pip` can use to manage installing/uninstalling your project.

[1]: https://packaging.python.org/tutorials/packaging-projects/

**Comment by BolieRide** [comment]
Added the setup.py.  I think I filled everything in correctly.  I had to double check how the long description was filled in.  Apparently it is populated via the README.md file.

**Comment by JnyJny** [comment]
Good start, but you need to test your files before you close the issue :)

Looks like the `packages` and `package_dir` variables in *setup.py* are not quite right:
```python
    package_dir={"": "src"},
    packages=setuptools.find_packages(where="src"),
```

Error when trying to use the setup.py to install the package:

```console
$ source .venv/bin/activate.csh
(.venv) $ python3 -m pip install -e .
Obtaining file:///Users/ejo/clients/heather/colorpicker
Installing collected packages: Colorpicker-BolieRide
  Running setup.py develop for Colorpicker-BolieRide
    ERROR: Command errored out with exit status 1:
     command: /Users/ejo/clients/heather/colorpicker/.venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/ejo/clients/heather/colorpicker/setup.py'"'"'; __file__='"'"'/Users/ejo/clients/heather/colorpicker/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/ejo/clients/heather/colorpicker/
    Complete output (2 lines):
    running develop
    error: error in 'egg_base' option: 'src' does not exist or is not a directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/ejo/clients/heather/colorpicker/.venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/ejo/clients/heather/colorpicker/setup.py'"'"'; __file__='"'"'/Users/ejo/clients/heather/colorpicker/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by BolieRide** [comment]
I believe I have fix it.  the src directory needed to be changed to colorpicker.  I also had to add .colorpicker_bolieride.egg_base to .gitignore.

**Comment by JnyJny** [comment]
I can confirm that the package now installs correctly in editable mode. _Now_ I'll close this issue since the problem has been addressed :)

**Comment by BolieRide** [comment]
Workflow question...
when I get an issue, so I simply comment and wait for the user who opened
it to close?

**Comment by JnyJny** [comment]
Yes, it’s a dialog between the person that opened the issue (identifying a problem) and the person fixing the problem. I find it rude when a developer closes an issue without confirming that the problem is fixed with the originator of the issue.

(You aren’t rude, you just didn’t know and that’s ok!)

Erik
