### ISSUE TITLE
Add `requirements-dev.txt`

### ISSUE THREAD

**Issue by JnyJny** [BolieRide/colorpicker#4]
Projects typically have installation requirements and development requirements; the installation requirements are third party packages that this package requires to function correctly.  Development requirements are packages that used during development but not installed by the end user.

Create a `requirements-dev.txt` file in the project top-level directory and add `pytest` to it:

```
pytest
```

The file can then be used to install development requirements into a virtual (or any) python environment. If you are using a virtual environment, make sure to activate it first before installing.

```console
$ python3 -m pip install -r requirements-dev.txt
```

`pytest` is a third-party python testing package which I prefer over the standard library `unittest` testing module and we'll use it to build some tests to make sure your project is working the way you intend it to work.

**Comment by BolieRide** [comment]
I have added this file and the pytest inside.
